// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AnnoBibLibraryMac.CustomControls;

namespace AnnoBibLibraryMac
{
    public partial class EditableOutlineView : NSOutlineView
    {
        public EditableOutlineView(IntPtr handle) : base(handle) { }

        public EventHandler<DeletePressedEventArgs> OnRowDelete { get; set; }

        public override void KeyDown(NSEvent theEvent)
        {
            base.KeyDown(theEvent);

            if (theEvent.KeyCode == (int)NSKey.Delete)
            {
                if (GetView(0, SelectedRow, false) is IEditableView view)
                {
                    if (view.IsBeingEdited) return;
                    if (!view.CanBeDeleted) return;

                    var alert = new NSAlert
                    {
                        MessageText = "Delete?",
                        InformativeText = "",
                        AlertStyle = NSAlertStyle.Warning,
                    };

                    alert.AddButton("Yes"); alert.AddButton("No");

                    if (alert.RunModal() == 1000)
                    {
                        OnRowDelete(GetView(0, SelectedRow, false), new DeletePressedEventArgs((int)SelectedRow));
                    }
                }
            }
        }
    }
}
