// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AnnoBibLibraryMac.CustomControls;

namespace AnnoBibLibraryMac
{
    public class DeletePressedEventArgs : EventArgs
    {
        public DeletePressedEventArgs(int row) { SelectedRow = row; }
        public int SelectedRow { get; }
    }

    public partial class TableViewKeywordGroups : NSTableView
    {
        public TableViewKeywordGroups (IntPtr handle) : base (handle)
        {
        }

        public EventHandler<DeletePressedEventArgs> OnDeletePressed { get; set; }

        public override void KeyUp(NSEvent theEvent)
        {
            base.KeyUp(theEvent);

            if(theEvent.KeyCode == (int)NSKey.Delete)
            {
                IEditableView view = (IEditableView)GetView(0, SelectedRow, false);
                if(!view.CanBeDeleted || view.IsBeingEdited)
                    return;

                OnDeletePressed(this, new DeletePressedEventArgs((int)this.SelectedRow));

            }
        }
    }
}
