// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AnnoBibLibraryMac.DataSources;
using AnnoBibLibrary.Shared;
using AnnoBibLibraryMac.ViewDelegates;

namespace AnnoBibLibraryMac
{
	public partial class PreferencesViewController : NSViewController
	{
        #region Properties
        private DataSourceTableViewKeywordGroups DataSourceKeywordGroups { get; set; }
        private Library OpenLibrary { get; } = GlobalResources.OpenLibrary;
        #endregion

        public PreferencesViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            DataSourceKeywordGroups = new DataSourceTableViewKeywordGroups();
            foreach (string kwd in OpenLibrary.KeywordGroupsFormatted)
                DataSourceKeywordGroups.Keywords.Add(new Tuple<string, bool>(kwd, false));

            TableViewKeywordGroups.DataSource = DataSourceKeywordGroups;
            TableViewKeywordGroups.Delegate = new DelegateTableViewKeywordGroups(DataSourceKeywordGroups);
        }

        partial void OnAddKeywordGroup(NSObject sender)
        {
            DataSourceKeywordGroups.Keywords.Add(new Tuple<string, bool>("", true));
            TableViewKeywordGroups.ReloadData();
        }

        partial void OnAccept(NSObject sender)
        {
            string[] keywords = new string[DataSourceKeywordGroups.Keywords.Count];

            for (var i = 0; i < keywords.Length; ++i)
                keywords[i] = DataSourceKeywordGroups.Keywords[i].Item1;

            OpenLibrary.SetKeywordGroups(keywords);
            NSApplication.SharedApplication.KeyWindow.Close();
        }
    }
}
