// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AnnoBibLibraryMac.DataSources;
using AnnoBibLibraryMac.ViewDelegates;

namespace AnnoBibLibraryMac
{
	public partial class PreferencesViewController : NSViewController
	{
		public PreferencesViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            DataSourceTableViewKeywordGroups keywordGroups = new DataSourceTableViewKeywordGroups();

            keywordGroups.Keywords.Add("People");
            keywordGroups.Keywords.Add("Places");
            keywordGroups.Keywords.Add("Concepts");

            TableViewKeywordGroups.DataSource = keywordGroups;
            TableViewKeywordGroups.Delegate = new DelegateTableViewKeywordGroups(keywordGroups);
        }
    }
}
