// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AnnoBibLibraryMac.DataSources;
using AnnoBibLibraryMac.ViewDelegates;
using AnnoBibLibrary.Shared;

namespace AnnoBibLibraryMac
{
	public partial class PreferencesViewController : NSViewController
	{
        #region Private Properties
        private Library OpenLibrary { get; set; }
        #endregion

        public PreferencesViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            OpenLibrary = GlobalResources.OpenLibrary;

            DataSourceTableViewKeywordGroups keywordGroups = new DataSourceTableViewKeywordGroups();

            keywordGroups.Keywords.AddRange(OpenLibrary.DefaultKeywordGroupsFormatted);

            TableViewKeywordGroups.DataSource = keywordGroups;
            TableViewKeywordGroups.Delegate = new DelegateTableViewKeywordGroups(keywordGroups);
        }
    }
}
