// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AnnoBibLibrary.Shared;
using AnnoBibLibraryMac.DataSources;
using AnnoBibLibraryMac.ControlDelegates;
using AnnoBibLibrary.Shared.Fields;
using AnnoBibLibrary.Shared.Bibliography;
using AnnoBibLibraryMac.CustomControls;

namespace AnnoBibLibraryMac
{
	public partial class NewSourceViewController : NSViewController
	{
		public NewSourceViewController (IntPtr handle) : base (handle)
		{
		}

        DataSourceOutlineViewSourceFields DataSource = new DataSourceOutlineViewSourceFields();

        public Source EditingSource = null;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            string[] citationFormatsStr = GlobalResources.CitationFormatsFormatted;
            NSString[] citationValues = new NSString[citationFormatsStr.Length];
            for (int i = 0; i < citationValues.Length; ++i)
                citationValues[i] = new NSString(citationFormatsStr[i]);

            ComboBoxFormats.Add(citationValues);

            OutlineViewSourceFields.DataSource = DataSource;
            OutlineViewSourceFields.Delegate = new DelegateOutlineViewSourceFields(DataSource);

            OutlineViewSourceFields.OnRowDelete += (sender, e) =>
            { 
                var index = e.SelectedRow;
                foreach(var fieldGroup in DataSource.FieldInfo)
                {
                    if(!fieldGroup.IsExpandable)
                        --index; 

                    else
                    {
                        foreach(var field in fieldGroup.Fields)
                        {
                            --index;
                            if (index == 0)
                            {
                                fieldGroup.Fields.Remove(field);
                                break;
                            }
                        }
                    }

                    if (index == 0) break;
                }

                OutlineViewSourceFields.ReloadData();
            };

            ComboBoxFormats.SelectItem(0);
            FormatSourceFields(GlobalResources.GetFormat("Print"));
        }

        #region XCode Methods
        partial void OnTitleUnknownCheck(NSObject sender)
        {
            if (((NSButton)sender).State == NSCellStateValue.Off)
                TextFieldTitle.Enabled = true;

            else TextFieldTitle.Enabled = false;
        }

        partial void OnFormatChange(NSObject sender)
        {
            FormatSourceFields(GlobalResources.GetFormat(ComboBoxFormats.SelectedValue.ToString()));
        }

        partial void OnAccept(NSObject sender)
        {
            if (EditingSource == null)
            {
                string format = ((NSString)ComboBoxFormats.SelectedValue).LocalizedCapitalizedString;
                Source source = new Source(GlobalResources.GetFormat(format));
                foreach(var fieldGroup in DataSource.FieldInfo)
                {
                    if (fieldGroup.IsExpandable)
                    {
                        IComparable[] values = new IComparable[fieldGroup.Fields.Count - 1];
                        for (int i = 0; i < values.Length - 1; ++i)
                            values[i] = fieldGroup.Fields[i].Value;

                        source.SetValues(fieldGroup.FieldInfo.Name, values);
                    }

                    else source.SetValues(fieldGroup.FieldInfo.Name, fieldGroup.Value);
                }

                GlobalResources.OpenLibrary.AddSource(source);
            }
        }
        #endregion

        #region Private Methods
        private void FormatSourceFields(CitationFormat format)
        {
            DataSource.FieldInfo.Clear();
            foreach(var fieldInfo in format.Fields) 
            {
                if (fieldInfo.Name.ToLower() != "title")
                {
                    DataSource.FieldInfo.Add(
                        new DataSourceOutlineViewSourceFieldsInfo(
                            fieldInfo
                        )
                    );
                }
            }

            OutlineViewSourceFields.ReloadData();
        }
        #endregion
    }
}
